// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfjdMuqmeBbSQJQSOtGUhNO7bbTB_iCwk',
    appId: '1:915797787017:web:739a9dd2c7ffe2b2c5a158',
    messagingSenderId: '915797787017',
    projectId: 'chat-app-1ca3a',
    authDomain: 'chat-app-1ca3a.firebaseapp.com',
    storageBucket: 'chat-app-1ca3a.firebasestorage.app',
    measurementId: 'G-L70TZ324B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLHghubgCP4zhz58rGPFAGRGPa298GF14',
    appId: '1:915797787017:android:8fddccfaf3500af1c5a158',
    messagingSenderId: '915797787017',
    projectId: 'chat-app-1ca3a',
    storageBucket: 'chat-app-1ca3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7tQyEAEh52ileNs0OcaKVEWxfRzfWML0',
    appId: '1:915797787017:ios:6540a468958518b9c5a158',
    messagingSenderId: '915797787017',
    projectId: 'chat-app-1ca3a',
    storageBucket: 'chat-app-1ca3a.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7tQyEAEh52ileNs0OcaKVEWxfRzfWML0',
    appId: '1:915797787017:ios:6540a468958518b9c5a158',
    messagingSenderId: '915797787017',
    projectId: 'chat-app-1ca3a',
    storageBucket: 'chat-app-1ca3a.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfjdMuqmeBbSQJQSOtGUhNO7bbTB_iCwk',
    appId: '1:915797787017:web:b7f5d4a60b7ff280c5a158',
    messagingSenderId: '915797787017',
    projectId: 'chat-app-1ca3a',
    authDomain: 'chat-app-1ca3a.firebaseapp.com',
    storageBucket: 'chat-app-1ca3a.firebasestorage.app',
    measurementId: 'G-NTF3RBY1M5',
  );
}
